# IM Gateway 配置
# 主要配置已迁移到Nacos配置中心
# 本地只保留必要的基础配置

spring:
  application:
    name: im-gateway
  cloud:
    compatibility-verifier:
      enabled: false

# 本地保留的基础配置
# 其他配置已迁移到Nacos配置中心：
# - 数据库配置 -> common-database.yml
# - Redis配置 -> common-redis.yml
# - RocketMQ配置 -> common-rocketmq.yml
# - 服务特有配置 -> im-gateway-dev.yml

# 日志配置
logging:
  level:
    com.alibaba.nacos: INFO
    org.springframework.cloud: DEBUG
