server:
  port: 8080
  node-id: gateway-node-1  # 服务器节点ID，在分布式环境中每个节点应不同

spring:
  application:
    name: im-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im-plus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: vanky
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  # Redis配置
  data:
    redis:
      host: 192.168.200.137
      port: 6379
      database: 0
      password: 123456
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 20
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 5

# Netty 服务器配置
netty:
  server:
    # TCP 服务器配置
    tcp:
      enabled: true
      port: 8900
    # UDP 服务器配置
    udp:
      enabled: true
      port: 8901
    # WebSocket 服务器配置
    websocket:
      enabled: true
      port: 8902
      path: /websocket

# RocketMQ配置
rocketmq:
  name-server: 192.168.200.137:9876
  producer:
    group: im-gateway-producer-group
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    retry-next-server: true
  # 推送消息消费者配置
  push-consumer:
    group: im-gateway-push-consumer-group
    consume-thread-min: 5
    consume-thread-max: 20
    consume-message-batch-max-size: 1
    consume-timeout: 15000
    max-reconsume-times: 3

# 消息配置
message:
  push:
    topic: TOPIC_PUSH_TO_GATEWAY
