# IM Message Server 本地配置（降级方案）
# 当Nacos不可用时，使用此配置文件
# 使用方式：--spring.profiles.active=local

server:
  port: 8100
  
spring:
  application:
    name: im-message-server
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        enabled: false  # 禁用Nacos服务发现
      config:
        enabled: false  # 禁用Nacos配置中心
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im-plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: vanky
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2

  data:
    redis:
      host: 192.168.10.6
      port: 6379
      database: 0
      password: 123456
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# RocketMQ配置
rocketmq:
  name-server: 192.168.10.6:9876
  producer:
    group: im-message-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 2
    retry-next-server: true
    compress-message-body-threshold: 4096
    max-message-size: 4194304
  consumer:
    group: im-message-consumer-group
    group-private: im-message-consumer-group-private
    group-group: im-message-consumer-group-group
    consume-timeout: 15000
    max-reconsume-times: 3
    consume-thread-min: 5
    consume-thread-max: 20
    consume-message-batch-max-size: 1
    ack:
      consume-thread-min: 10
      consume-thread-max: 30
      consume-timeout: 10000
      max-reconsume-times: 3
      consume-message-batch-max-size: 10

# 消息推送配置
message:
  push:
    topic: TOPIC_PUSH_TO_GATEWAY

# Feign客户端配置
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
      im-user:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
  retryer:
    enabled: true
    period: 1000
    max-period: 3000
    max-attempts: 3

# 日志配置
logging:
  level:
    com.vanky.im.message.client: DEBUG
    feign: DEBUG
