server:
  port: 8101
  
spring:
  application:
    name: im-message-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im-plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: vanky
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2

  # Redis配置
  data:
    redis:
      host: 192.168.200.137
      port: 6379
      database: 0
      password: 123456
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 20
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 5

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vanky.im.message.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# RocketMQ配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: im-message-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 2
    retry-next-server: true
    compress-message-body-threshold: 4096
    max-message-size: 4194304
  consumer:
    # 默认消费者组配置，但实际使用TopicConstants中的常量
    group: im-message-consumer-group
    # 私聊消息消费者组
    group-private: im-message-consumer-group-private
    # 群聊消息消费者组
    group-group: im-message-consumer-group-group
    consume-timeout: 15000
    max-reconsume-times: 3
    consume-thread-min: 5
    consume-thread-max: 20
    consume-message-batch-max-size: 1

# 消息推送配置
message:
  push:
    topic: TOPIC_PUSH_TO_GATEWAY

