# IM Sequence Service 配置
# 主要配置已迁移到Nacos配置中心
# 本地只保留必要的基础配置

spring:
  application:
    name: im-sequence
  cloud:
    compatibility-verifier:
      enabled: false

# 本地保留的基础配置
# 其他配置已迁移到Nacos配置中心：
# - 数据库配置 -> common-database.yml
# - Redis配置 -> common-redis.yml  
# - 服务特有配置 -> im-sequence-dev.yml

# 日志配置
logging:
  level:
    com.alibaba.nacos: INFO
    org.springframework.cloud: DEBUG
